name = "MPSSpinBoson"
uuid = "931477e6-3083-49bf-99eb-cdbbf621674e"
authors = ["Dario Tamascelli"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
